#!/bin/sh
# alias j='z'
# alias f='zi'
#alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias nvimdot='nvim ~/dotfiles/'
alias nvimjournal='nvim ~/.nvim_journal'

# ASCII aquarium art
alias aq="asciiquarium"
alias feh='feh -d --scale-down'

# Tmux alias
alias tn='tmux new-session'
alias ta='tmux attach'
alias tmuxstart="~/.config/tmux/start_session.sh"
alias tmuxkill="tmux kill-session"

# Sort entries when using ls
alias ls='ls --group-directories-first --color=auto'

#alias fzf='~/useful_scripts/fzfimg.sh'
alias sublime='~/dev/sublime_text/sublime_text'

# command to retrieve current public ip
alias myip="curl https://ipinfo.io"

# Lists all installed packages and the related info
# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Browsing_packages
alias pacman-packages="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
alias pacman-packages-upgradable="pacman -Qu | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"


alias print-colors="$SHELL $ZDOTDIR/print_colors.sh"

function cheatsheet() {
  curl -s cht.sh/$1 | less
}

function changetheme() {
  wal --theme | fzf --preview='$SHELL $ZDOTDIR/print_colors.sh' --bind 'enter:execute(wal -e --theme $(echo {} | sed "s/ - //") > /dev/null)'
}

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# force vt100 when using ssh
alias ssh='TERM=vt100 ssh' 

#alias manpdf='man -k . | dmenu -l 20 | awk '"'"'{ print $1}'"'"' | xargs -r man -Tpdf | zathura -'
manpdf_helper() {
  if [ "$1" = "" ]; then
    man -k . | dmenu -l 20 | awk '{ print $1}' | xargs -r man -Tpdf | zathura -;
  else
    man -Tpdf $1 | zathura -;
  fi
}
alias manpdf=manpdf_helper
compdef manpdf=man
