#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
# use nvim for man pages
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export DOTFILES="$HOME/dotfiles"
export NVIMJOURNAL="$HOME/.nvim_journal"
export DEV="$HOME/dev"
#export PATH=$HOME/.cargo/bin:$PATH
#export PATH=$HOME/.local/share/go/bin:$PATH
#export GOPATH=$HOME/.local/share/go
#export PATH=$HOME/.fnm:$PATH
#export PATH="$PATH:./node_modules/.bin"
#eval "$(fnm env)"
#eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
