#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
export HISTSIZE=1000000
export SAVEHIST=1000000

# Environment variables
export EDITOR="nvim"
export VISUAL="nvim"
export SUDO_EDITOR="nvim"
export DIFFPROG='nvim -d'

export PATH="$HOME/.local/bin":$PATH

# use nvim for man pages
# requires: https://github.com/vim-utils/vim-man
export MANPAGER='nvim +Man!'
export MANWIDTH=999
# override this in zsh-exports.local if necessary
export DOTFILES="$HOME/dotfiles"
export USEFUL_SCRIPTS="$HOME/useful_scripts"
export NVIMJOURNAL="$HOME/.nvim_journal"
export DEV="$HOME/dev"

export STARSHIP_CONFIG=~/.config/starship/starship.toml
[ -d $HOME/.cargo/bin ] && export PATH=$HOME/.cargo/bin:$PATH

# Disable cowsay for ansible playbooks
export ANSIBLE_NOCOWS=1
#export PATH=$HOME/.local/share/go/bin:$PATH
#export GOPATH=$HOME/.local/share/go
#export PATH=$HOME/.fnm:$PATH
#export PATH="$PATH:./node_modules/.bin"
#eval "$(fnm env)"
#eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

[ -f "$ZDOTDIR/zsh-exports.local" ] && source "$ZDOTDIR/zsh-exports.local"
