#!/bin/sh
# alias j='z'
# alias f='zi'
#alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias nvimdot='nvim $DOTFILES'
alias nvimjournal='nvim ~/.nvim_journal/.nvim_journal.md +VimwikiDiaryIndex'
alias nvimclean='NVIM_APPNAME=nvim_clean nvim'

# command to retrieve current public ip
alias myip="curl https://ipinfo.io"

# Lists all installed packages and the related info
# https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Browsing_packages
alias pacman-packages="pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"
alias pacman-packages-upgradable="pacman -Qu | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'"

# ASCII aquarium art
alias aq="asciiquarium"
alias feh='feh -d --scale-down'

# Tmux alias
# alias tn='tmux new-session'
# alias ta='tmux attach'
alias tmuxstart="~/.config/tmux/start_session.sh"
alias tmuxkill="tmux kill-session"

alias vlcwithhttp="vlc -I http --http-host 0.0.0.0 --http-port 8081 --http-password vlc"

# use bat instead of cat
# see https://github.com/sharkdp/bat
alias cat='bat'

# open rust book locally
alias rustbook='rustup docs --book'

# Sort entries when using ls
alias ls='ls --group-directories-first --color=auto'

alias make="make -j 4"

alias viu="viu -h 40"

# start firefox process in background
# immediately disown it (so it doesn't close when the terminal closes)
# and redirect all output to /dev/null
alias twitchchat="firefox --new-window -P twitch --kiosk \"https://www.twitch.tv/popout/linus045/chat?popout=\" >/dev/null 2>&1 & disown"

# https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh
#alias fzf='~/useful_scripts/fzfimg.sh'

# prints a color table (to verify the current color scheme)
alias print-colors="$SHELL $ZDOTDIR/print_colors.sh"

# prints out the result from 
function cheatsheet() {
  curl -s cht.sh/$1 | less -R
}

# change with via fzf and ENTER
function changetheme() {
  wal --theme | fzf --preview='$SHELL $ZDOTDIR/print_colors.sh; printf "\n\n\nUsage: Press ENTER to change"' --bind 'enter:execute(wal -e --theme $(echo {} | sed -r "s/ - ([a-zA-Z0-9_-]+).*/\1/") > /dev/null)'
}

# get fastest mirrors
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk and memory
alias df='df -h'     # human-readable sizes
alias free='free -h' # show sizes human-readable

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

alias   ..='cd ..'
alias  ...='cd ../../'
alias ....='cd ../../../'

# force vt100 when using ssh (sets terminal emulator so flashing/bell/etc is outputted correctly)
# see: https://it.engineering.oregonstate.edu/book/what-does-term-network-or-term-vt100-mean
#alias ssh='TERM=vt100 ssh' 

# kitty +kitty fixes problems some problems see: 
# https://wiki.archlinux.org/title/Kitty#Terminal_issues_with_SSH
# alias ssh="TERM=xterm kitty +kitten ssh"

#alias manpdf='man -k . | dmenu -l 20 | awk '"'"'{ print $1}'"'"' | xargs -r man -Tpdf | zathura -'
manpdf_helper() {
  if [ "$1" = "" ]; then
    man -k . | dmenu -l 20 | awk '{ print $1}' | xargs -r man -Tpdf | zathura -;
  else
    man -Tpdf $1 | zathura -;
  fi
}
alias manpdf=manpdf_helper
# sets autocomplete for manpdf equal to man's autocomplete
compdef manpdf=man


alias nvim-clean="NVIM_APPNAME=nvim_clean nvim"

function nvims() {
  items=("default" "nvim_clean" )
  config=$(printf "%s\n" "${items[@]}" | fzf --prompt=" Neovim Config  " --height=~50% --layout=reverse --border --exit-0)
  if [[ -z $config ]]; then
    echo "Nothing selected"
    return 0
  elif [[ $config == "default" ]]; then
    config=""
  fi
  NVIM_APPNAME=$config nvim $@
}

bindkey -s "^n" "nvims\n"
