#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
export HISTSIZE=1000000
export SAVEHIST=1000000

# Environment variables
export EDITOR="nvim"
export PATH="$HOME/.local/bin":$PATH

# use nvim for man pages
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export DOTFILES="$HOME/dotfiles"
export NVIMJOURNAL="$HOME/.nvim_journal"
export DEV="$HOME/dev"

export STARSHIP_CONFIG=~/.config/starship/starship.toml
export PATH=$HOME/.cargo/bin:$PATH

# Disable cowsay for ansible playbooks
export ANSIBLE_NOCOWS=1
#export PATH=$HOME/.local/share/go/bin:$PATH
#export GOPATH=$HOME/.local/share/go
#export PATH=$HOME/.fnm:$PATH
#export PATH="$PATH:./node_modules/.bin"
#eval "$(fnm env)"
#eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
