require("plugins.text_utils")
require("plugins.visual_editor_utils")
require("plugins.autocomplete")
require("plugins.debugger")
require("plugins.git")
require("plugins.interface")
require("plugins.lsp")
require("plugins.plugin_tooling")
require("plugins.special")
require("plugins.startup")
require("plugins.telescope")
require("plugins.text_utils")
return {}
